version: '3'
services:
  redis:
    container_name: red
    image: redis:5
    ports:
      - 6379:6379
  postgres:
    container_name: pg
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
